package com.health.care.lab.appointment.enums;
 public enum TestType {
   CRP,ESR,CREATININE,ELECTROLYTES,FASTING_BLOOD_SUGAR,FASTING_BLOOD_COUNT,
   HBA1C,UREA,LIPID_PROFILE,MICROALBUMIN,TSH,DENGUE_ANTIGEN
 }
